# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
malaysia_cities = [
  {:name => 'Port Dickson', :state_name => 'Negeri Sembilan'},
  {:name => 'Bahau', :state_name => 'Negeri Sembilan'},
  {:name => 'Rompin', :state_name => 'Negeri Sembilan'},
  {:name => 'Gemas', :state_name => 'Negeri Sembilan'},
  {:name => 'Seremban', :state_name => 'Negeri Sembilan'},
  {:name => 'Rembau', :state_name => 'Negeri Sembilan'},
  {:name => 'Sri Menanti', :state_name => 'Negeri Sembilan'},
  {:name => 'Simpang Pertang', :state_name => 'Negeri Sembilan'},
  {:name => 'Kuala Pilah', :state_name => 'Negeri Sembilan'},
  {:name => 'Kuala Klawang', :state_name => 'Negeri Sembilan'},
  {:name => 'Johol', :state_name => 'Negeri Sembilan'},
  {:name => 'Jelebu', :state_name => 'Negeri Sembilan'},
  {:name => 'Jempol', :state_name => 'Negeri Sembilan'},
  {:name => 'Bandar Baru Serting', :state_name => 'Negeri Sembilan'},
  {:name => 'Ipoh', :state_name => 'Perak'},
  {:name => 'Bukit Merah', :state_name => 'Perak'},
  {:name => 'Sitiawan', :state_name => 'Perak'},
  {:name => 'Lumut', :state_name => 'Perak'},
  {:name => 'Tapah', :state_name => 'Perak'},
  {:name => 'Slim River', :state_name => 'Perak'},
  {:name => 'Perak Tengah', :state_name => 'Perak'},
  {:name => 'Gerik', :state_name => 'Perak'},
  {:name => 'Parit Buntar', :state_name => 'Perak'},
  {:name => 'Teluk Batik', :state_name => 'Perak'},
  {:name => 'Bagan Datuk', :state_name => 'Perak'},
  {:name => 'Sungkai', :state_name => 'Perak'},
  {:name => 'Teluk Intan', :state_name => 'Perak'},
  {:name => 'Kuala Kangsar', :state_name => 'Perak'},
  {:name => 'Batu Gajah', :state_name => 'Perak'},
  {:name => 'Pangkor Island', :state_name => 'Perak'},
  {:name => 'Tambun', :state_name => 'Perak'},
  {:name => 'Bidor', :state_name => 'Perak'},
  {:name => 'Taiping', :state_name => 'Perak'},
  {:name => 'Kampar', :state_name => 'Perak'},
  {:name => 'Sungai Siput', :state_name => 'Perak'},
  {:name => 'Kinta', :state_name => 'Perak'},
  {:name => 'Ayer Tawar', :state_name => 'Perak'},
  {:name =>  'Simpang', :state_name => 'Perak'},
  {:name => 'Kamunting', :state_name => 'Perak'},
  {:name =>"Ayer Keroh", :state_name =>"Melaka"},
  {:name =>"Tanjung Bidara", :state_name =>"Melaka"},
  {:name =>"Jasin", :state_name =>"Melaka"},
  {:name =>"Melaka Town", :state_name =>"Melaka"},
  {:name =>"Merlimau", :state_name =>"Melaka"},
  {:name =>"Masjid Tanah", :state_name =>"Melaka"},
  {:name =>"Alor Gajah", :state_name =>"Melaka"},
  {:name =>"Umbai", :state_name =>"Melaka"},
  {:name =>"Tampin", :state_name =>"Melaka"},
  {:name =>"Sungai Udang", :state_name =>"Melaka"},
  {:name =>"Tanjung Buncah", :state_name =>"Penang"},
  {:name =>"Georgetown", :state_name =>"Penang"},
  {:name =>"Bukit Jambul", :state_name =>"Penang"},
  {:name =>"Teluk Bahang", :state_name =>"Penang"},
  {:name =>"Butterworth", :state_name =>"Penang"},
  {:name =>"Batu Feringgi", :state_name =>"Penang"},
  {:name =>"Bayan Lepas", :state_name =>"Penang"},
  {:name =>"Jelutong", :state_name =>"Penang"},
  {:name =>"Seberang Perai", :state_name =>"Penang"},
  {:name =>"Bukit Mertajam", :state_name =>"Penang"},
  {:name =>"Nibong", :state_name =>"Penang"},
  {:name =>"Seberang Jaya", :state_name =>"Penang"},
  {:name =>"Kepala Batas", :state_name =>"Penang"},
  {:name =>"Balik Pulau", :state_name =>"Penang"},
  {:name =>"Pulau Langkawi", :state_name =>"Kedah"},
  {:name =>"Ayer Hitam", :state_name =>"Kedah"},
  {:name =>"Alor Setar", :state_name =>"Kedah"},
  {:name =>"Kulim", :state_name =>"Kedah"},
  {:name =>"Kuala Kedah", :state_name =>"Kedah"},
  {:name =>"Bandar Baharu", :state_name =>"Kedah"},
  {:name =>"Yan", :state_name =>"Kedah"},
  {:name =>"Bukit Kayu Hitam", :state_name =>"Kedah"},
  {:name =>"Baling", :state_name =>"Kedah"},
  {:name =>"Sungai Petani", :state_name =>"Kedah"},
  {:name =>"Jitra", :state_name =>"Kedah"},
  {:name =>"Kota Bharu", :state_name =>"Kelantan"},
  {:name =>"Kuala Krai", :state_name =>"Kelantan"},
  {:name =>"Jeli", :state_name =>"Kelantan"},
  {:name =>"Gua Musang", :state_name =>"Kelantan"},
  {:name =>"Tumpat", :state_name =>"Kelantan"},
  {:name =>"Kemubu", :state_name =>"Kelantan"},
  {:name =>"Tanah Merah", :state_name =>"Kelantan"},
  {:name =>"Pasir Puteh", :state_name =>"Kelantan"},
  {:name =>"Dabong", :state_name =>"Kelantan"},
  {:name =>"Kuala Balah", :state_name =>"Kelantan"},
  {:name =>"Melor", :state_name =>"Kelantan"},
  {:name =>"Bachok", :state_name =>"Kelantan"},
  {:name =>"Kuala Nerang", :state_name =>"Kelantan"},
  {:name =>"Pokok Sena", :state_name =>"Kelantan"},
  {:name =>"Pasir Mas", :state_name =>"Kelantan"},
  {:name =>"Segamat", :state_name =>"Johor"},
  {:name =>"Muar", :state_name =>"Johor"},
  {:name =>"Yong Peng", :state_name =>"Johor"},
  {:name =>"Endau Rompin", :state_name =>"Johor"},
  {:name =>"Kluang", :state_name =>"Johor"},
  {:name =>"Pasir Gudang", :state_name =>"Johor"},
  {:name =>"Tangkak", :state_name =>"Johor"},
  {:name =>"Batu Pahat", :state_name =>"Johor"},
  {:name =>"Labis", :state_name =>"Johor"},
  {:name =>"Kota Tinggi", :state_name =>"Johor"},
  {:name =>"Johor Bahru", :state_name =>"Johor"},
  {:name =>"Pontian", :state_name =>"Johor"},
  {:name =>"Pagoh", :state_name =>"Johor"},
  {:name =>"Ayer Hitam", :state_name =>"Johor"},
  {:name =>"Mersing", :state_name =>"Johor"},
  {:name =>"Senai", :state_name =>"Johor"},
  {:name =>"Desaru", :state_name =>"Johor"},
  {:name =>"Skudai", :state_name =>"Johor"},
  {:name =>"Kulai", :state_name =>"Johor"},
  {:name =>"Ulu Tiram", :state_name =>"Johor"},
  {:name =>"Ledang", :state_name =>"Johor"},
  {:name =>"Kangar", :state_name =>"Perlis"},
  {:name =>"Arau", :state_name =>"Perlis"},
  {:name =>"Kuala Perlis", :state_name =>"Perlis"},
  {:name =>"Kg Salang", :state_name =>"Perlis"},
  {:name =>"Simpang Empat", :state_name =>"Perlis"},
  {:name =>"Beseri", :state_name =>"Perlis"},
  {:name =>"Cameron Highlands", :state_name =>"Pahang"},
  {:name =>"Kuala Tahan", :state_name =>"Pahang"},
  {:name =>"Raub", :state_name =>"Pahang"},
  {:name =>"Karak", :state_name =>"Pahang"},
  {:name =>"Chenor", :state_name =>"Pahang"},
  {:name =>"Tasik Bera", :state_name =>"Pahang"},
  {:name =>"Kuantan", :state_name =>"Pahang"},
  {:name =>"Kg New Zealand", :state_name =>"Pahang"},
  {:name =>"Berserah", :state_name =>"Pahang"},
  {:name =>"Kuala Rompin", :state_name =>"Pahang"},
  {:name =>"Pekan", :state_name =>"Pahang"},
  {:name =>"Kuala Lipis", :state_name =>"Pahang"},
  {:name =>"Taman Negara", :state_name =>"Pahang"},
  {:name =>"Bentong", :state_name =>"Pahang"},
  {:name =>"Lanchang", :state_name =>"Pahang"},
  {:name =>"Temerloh", :state_name =>"Pahang"},
  {:name =>"Sungai Lembing", :state_name =>"Pahang"},
  {:name =>"Gambang", :state_name =>"Pahang"},
  {:name =>"Cherating", :state_name =>"Pahang"},
  {:name =>"Tasik Chini", :state_name =>"Pahang"},
  {:name =>"Kuala Tembeling", :state_name =>"Pahang"},
  {:name =>"Frasers Hill", :state_name =>"Pahang"},
  {:name =>"Genting Highlands", :state_name =>"Pahang"},
  {:name =>"Mentakab", :state_name =>"Pahang"},
  {:name =>"Jerantut", :state_name =>"Pahang"},
  {:name =>"Triang", :state_name =>"Pahang"},
  {:name =>"Maran", :state_name =>"Pahang"},
  {:name =>"Panching", :state_name =>"Pahang"},
  {:name =>"Bandar Muadzam", :state_name =>"Pahang"},
  {:name =>"Pulau Tioman", :state_name =>"Pahang"},
  {:name =>"Sabak Bernam", :state_name =>"Selangor"},
  {:name =>"Kuala Langat", :state_name =>"Selangor"},
  {:name =>"Sepang", :state_name =>"Selangor"},
  {:name =>"Kota Kemuning", :state_name =>"Selangor"},
  {:name =>"Damansara Utama", :state_name =>"Selangor"},
  {:name =>"Puchong", :state_name =>"Selangor"},
  {:name =>"Cyberjaya", :state_name =>"Selangor"},
  {:name =>"Shah Alam", :state_name =>"Selangor"},
  {:name =>"Ulu Yam", :state_name =>"Selangor"},
  {:name =>"Klang", :state_name =>"Selangor"},
  {:name =>"Bangi", :state_name =>"Selangor"},
  {:name =>"Pulau Ketam", :state_name =>"Selangor"},
  {:name =>"Dengkil", :state_name =>"Selangor"},
  {:name =>"Subang Jaya", :state_name =>"Selangor"},
  {:name =>"Serdang", :state_name =>"Selangor"},
  {:name =>"Tanjung Malim", :state_name =>"Selangor"},
  {:name =>"Semenyih", :state_name =>"Selangor"},
  {:name =>"Kapar", :state_name =>"Selangor"},
  {:name =>"Kajang", :state_name =>"Selangor"},
  {:name =>"Sungai Buloh", :state_name =>"Selangor"},
  {:name =>"Banting", :state_name =>"Selangor"},
  {:name =>"Seri Kembangan", :state_name =>"Selangor"},
  {:name =>"Rawang", :state_name =>"Selangor"},
  {:name =>"Kuala Kubu", :state_name =>"Selangor"},
  {:name =>"Kuala Selangor", :state_name =>"Selangor"},
  {:name =>"Casey's Island", :state_name =>"Selangor"},
  {:name =>"Petaling Jaya", :state_name =>"Selangor"},
  {:name =>"Damansara", :state_name =>"Kuala Lumpur"},
  {:name =>"Selayang", :state_name =>"Kuala Lumpur"},
  {:name =>"Sentul", :state_name =>"Kuala Lumpur"},
  {:name =>"Sri Petaling", :state_name =>"Kuala Lumpur"},
  {:name =>"Damansara Heights", :state_name =>"Kuala Lumpur"},
  {:name =>"Sri Hartamas", :state_name =>"Kuala Lumpur"},
  {:name =>"Putrajaya", :state_name =>"Kuala Lumpur"},
  {:name =>"Bangsar", :state_name =>"Kuala Lumpur"},
  {:name =>"Brickfields", :state_name =>"Kuala Lumpur"},
  {:name =>"Batu Caves", :state_name =>"Kuala Lumpur"},
  {:name =>"Gombak", :state_name =>"Kuala Lumpur"},
  {:name =>"Sungai Besi", :state_name =>"Kuala Lumpur"},
  {:name =>"Salak South", :state_name =>"Kuala Lumpur"},
  {:name =>"Cheras", :state_name =>"Kuala Lumpur"},
  {:name =>"Kepong", :state_name =>"Kuala Lumpur"},
  {:name =>"Kuala Lumpur", :state_name =>"Kuala Lumpur"},
  {:name =>"Ampang", :state_name =>"Kuala Lumpur"},
  {:name =>"Lawas", :state_name =>"Sarawak"},
  {:name =>"Mulu National Park", :state_name =>"Sarawak"},
  {:name =>"Sarikei", :state_name =>"Sarawak"},
  {:name =>"Miri", :state_name =>"Sarawak"},
  {:name =>"Batang Ai National Park", :state_name =>"Sarawak"},
  {:name =>"Sibu", :state_name =>"Sarawak"},
  {:name =>"Kapit", :state_name =>"Sarawak"},
  {:name =>"Bareo", :state_name =>"Sarawak"},
  {:name =>"Bako National Park", :state_name =>"Sarawak"},
  {:name =>"Sri Aman", :state_name =>"Sarawak"},
  {:name =>"Bau", :state_name =>"Sarawak"},
  {:name =>"Samarahan", :state_name =>"Sarawak"},
  {:name =>"Kuching", :state_name =>"Sarawak"},
  {:name =>"Kabong", :state_name =>"Sarawak"},
  {:name =>"Bintulu", :state_name =>"Sarawak"},
  {:name =>"Kuala Terengganu", :state_name =>"Terengganu"},
  {:name =>"Pulau Redang", :state_name =>"Terengganu"},
  {:name =>"Kemaman", :state_name =>"Terengganu"},
  {:name =>"Dungun", :state_name =>"Terengganu"},
  {:name =>"Pulau Duyong", :state_name =>"Terengganu"},
  {:name =>"Rantau Abang", :state_name =>"Terengganu"},
  {:name =>"Kuala Besut", :state_name =>"Terengganu"},
  {:name =>"Pulau Kapas", :state_name =>"Terengganu"},
  {:name =>"Pulau Perhentian", :state_name =>"Terengganu"},
  {:name =>"Marang", :state_name =>"Terengganu"},
  {:name =>"Besut", :state_name =>"Terengganu"},
  {:name =>"Setiu", :state_name =>"Terengganu"},
  {:name =>"Cukai", :state_name =>"Terengganu"},
  {:name =>"Sipadan", :state_name =>"Sabah"},
  {:name =>"Lahad Datu", :state_name =>"Sabah"},
  {:name =>"Danau", :state_name =>"Sabah"},
  {:name =>"Tenom", :state_name =>"Sabah"},
  {:name =>"Papar", :state_name =>"Sabah"},
  {:name =>"Tuaran", :state_name =>"Sabah"},
  {:name =>"Danum", :state_name =>"Sabah"},
  {:name =>"Tawau", :state_name =>"Sabah"},
  {:name =>"Kudat", :state_name =>"Sabah"},
  {:name =>"Keningau", :state_name =>"Sabah"},
  {:name =>"Gunung Kinabalu", :state_name =>"Sabah"},
  {:name =>"Kota Kinabalu", :state_name =>"Sabah"},
  {:name =>"Semporna", :state_name =>"Sabah"},
  {:name =>"Limbang", :state_name =>"Sabah"},
  {:name =>"Sandakan", :state_name =>"Sabah"},
  {:name =>"Kuala Penyu", :state_name =>"Sabah"},
  {:name =>"Kinabalu National Park", :state_name =>"Sabah"},
  {:name =>"Penampang", :state_name =>"Sabah"},
  {:name =>"Kota Maruda", :state_name =>"Sabah"},
  {:name =>"Victoria", :state_name =>"Labuan"},
  {:name =>"Kampung Ganggarak", :state_name =>"Labuan"},
  {:name =>"Saratok", :state_name =>"Sarawak"}
  ]

malaysia_cities.each {|c| City.find_or_create_by_name(c)}
# --- city and state for malaysia END here ---